### ISSUE TITLE
Error while using this

### ISSUE THREAD

**Issue by PythonDjan** [Skidragon/react-hook-idle-timer-component#1]
hi

i tried to use this but showing error

![Error List](https://user-images.githubusercontent.com/64192463/81647104-18a24580-944a-11ea-893c-bc0a444ba92a.PNG)

![Error 2](https://user-images.githubusercontent.com/64192463/81647345-7f276380-944a-11ea-9e0a-92b729411a25.PNG)

![Error 3](https://user-images.githubusercontent.com/64192463/81647360-85b5db00-944a-11ea-9074-794692c49fda.PNG)

How can i solve this

**Comment by PythonDjan** [comment]
i Changes some code , Now showing these errors 

![Issue 1](https://user-images.githubusercontent.com/64192463/81655446-df6ed300-9453-11ea-915c-c3afdfeb6770.PNG)

![issue 2](https://user-images.githubusercontent.com/64192463/81655512-e990d180-9453-11ea-985a-53371e76d532.PNG)

**Comment by Skidragon** [comment]
Hi @PythonDjan, sorry I didn't see this sooner, I was just playing around with this but the reason why its giving errors in your typescript is because idleTimer has a null type rather than an interface. So to set this up for example:

```
const idleTimer = useRef<IdleTimerProps | HTMLElement>(null);
```
I'm using a generic above which you can research.
Also here is the reference to the typescript file:
https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.d.ts


Since the reference starts off as null, you will have to check if idleTimer is not null by wrapping it with an if statement then you can execute the method on it.

**Comment by PythonDjan** [comment]
> Hi @PythonDjan, sorry I didn't see this sooner, I was just playing around with this but the reason why its giving errors in your typescript is because idleTimer has a null type rather than a specific interface. So to set this up for example:
> 
> ```
> const idleTimer = useRef<IdleTimerProps>(null);
> ```
> 
> I'm using a generic above which you can research.
> Also here is the reference to the typescript file:
> https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.d.ts
> 
> Since the reference starts off as null, you will have to check if idleTimer is not null by wrapping it with an if statement then you can execute the method on it.

hi thank you for your reply.  Now its working.
